### ISSUE TITLE
AxMinions/GreatCrafts - Minion Crafter (BUG)

### ISSUE THREAD

**Issue by Aides123** [greatericontop/GreatCrafts#1]
Hi.
I've been testing custom recipes (64 x 9) and noticed that the “AxMinions” minion CRAFTER plugin (That is, the one that automatically creates designated things) doesn't work with this plugin.

I contacted the author of AxMinions about adding support for this plugin but he wrote back: Doesn't seem like the plugin has an api I could use.

Is it possible for you to add an API or add support for AxMinions yourself?

What is the error? Minion creates the designated item but does not follow the required amount and gives different numbers of items even though there should be enough items for 1 custom item, for example.

**Comment by greatericontop** [comment]
Since stacked item recipes aren't a vanilla feature, the plugin uses a craft event to change how many items get crafted. In this case, it's probably because the crafting isn't done "officially".

I can see if I can make some kind of API, but I'll need to know how the minion crafting works. Through which mechanism do the minions do the craft? Is it just like "if it has sufficient items then do the recipe" type thing?

**Comment by Aides123** [comment]
> Since stacked item recipes aren't a vanilla feature, the plugin uses a craft event to change how many items get crafted. In this case, it's probably because the crafting isn't done "officially".
> 
> I can see if I can make some kind of API, but I'll need to know how the minion crafting works. Through which mechanism do the minions do the craft? Is it just like "if it has sufficient items then do the recipe" type thing?

"In this case, it's probably because the crafting isn't done "officially"

The player sets in the GUI of the minion what item to craft. After selecting the item, the minion takes items from the chest and automatically craftes.


If you would like to see how it looks in the game, the plugin is free to download:
https://www.spigotmc.org/resources/axminions-the-all-in-one-minion-plugin.114766/updates

**Comment by greatericontop** [comment]
I'll get in contact with AxMinions and see what we can do.
